name="aces-api"
main="src/index.ts"

compatibility_date = "2022-11-22"

kv_namespaces = [
    { binding = "KV", id = "ca57fd4fad87497fb8c8deeead9d8f73", preview_id = "ca57fd4fad87497fb8c8deeead9d8f73" }
]

[vars]
COOKIE_NAME = "aces-auth"
COOKIE_PASSWORD = "PJhb_GceyJ0-c0db97eXAiOiJ-KV1Q-LiOiJIU/zI1NiJ9=" # should be secrets
CORS_ORIGIN = "http://localhost:8787;http://localhost:3000"

[[ d1_databases ]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "aces-data"
database_id = "f13e4747-0c58-4f1e-8a8e-2eda1bb5118c"
preview_database_id = "f13e4747-0c58-4f1e-8a8e-2eda1bb5118c"

[durable_objects]
bindings = [
    {name = "ACES_DURABLE", class_name = "AcesDurable"},
    {name = "TENANT_DURABLE", class_name = "TenantDurable"},
]

[[migrations]]
tag = "v1" # Should be unique for each entry
new_classes = ["AcesDurable", "TenantDurable"]
